#theme = "sunset"
#theme = "rose_pine"
#theme = "flexoki_light"
#theme = "flexoki_dark"
#theme = "catppuccin_frappe"
#theme = "kanagawa"
#theme = "gruvbox_light_hard"
theme = "ayu_mirage"
#theme = "flux"

[editor]
line-number = "relative"
mouse = true
auto-save = true
true-color = true
bufferline = "always"
soft-wrap.enable = true
rulers = [50, 72, 120]
end-of-line-diagnostics = "hint"

[editor.inline-diagnostics]
cursor-line = "error"

#[keys.normal]
# !git diff
#A-g = [ ":run-shell-command git diff" ]

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.indent-guides]
left = ["mode", "spinner", "version-control"]
render = true
character = "╎" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1

[editor.cursor-shape]
insert = "block"
normal = "bar"
select = "underline"

[editor.file-picker]
hidden = false
